from exampleenginepythonqiyhbwvw.common.field import Field

cod_producto = Field("cod_producto")
cod_iuc = Field("cod_iuc")
cod_titular = Field("cod_titular")
fec_alta = Field("fec_alta")
activo = Field("activo")
cod_client = Field("cod_client")
nombre = Field("nombre")
edad = Field("edad")
provincia = Field("provincia")
cod_postal = Field("cod_postal")
vip = Field("vip")
desc_producto = Field("desc_producto")
hash_col = Field("hash")
