from exampleenginepythonqiyhbwvw.common.field import Field

city_name = Field("city_name")
street_name = Field("street_name")
credit_card_number = Field("credit_card_number")
last_name = Field("last_name")
first_name = Field("first_name")
age = Field("age")
brand = Field("brand")
model = Field("model")
nfc = Field("nfc")
country_code = Field("country_code")
prime = Field("prime")
customer_vip = Field("customer_vip")
taxes = Field("taxes")
price_product = Field("price_product")
discount_amount = Field("discount_amount")
extra_discount = Field("extra_discount")
final_price = Field("final_price")
brands_top = Field("brands_top")
jwk_date = Field("jwk_date")
